"""Generate a focused Obsidian hot-context note from suspicious node ranking."""

from __future__ import annotations

import argparse
from pathlib import Path

from .graph_loader import load_graph
from .suspicious_nodes import DEFAULT_SELECTED_FILES, RankedNode, rank_suspicious_nodes

BUG_SUMMARY = (
    "`print_final_scores(...)` accepts score data through parameters but reads the "
    "module-level global `score` variable instead."
)


def _format_top_suspects(ranked_nodes: list[RankedNode], limit: int = 7) -> str:
    return "\n".join(
        (
            f"{node.rank}. `{node.node_id}` - score {node.total_score}; "
            f"{'; '.join(node.reasons)}"
        )
        for node in ranked_nodes[:limit]
    )


def _source_files(ranked_nodes: list[RankedNode], limit: int = 2) -> list[str]:
    files: list[str] = []
    for selected_file in DEFAULT_SELECTED_FILES:
        if any(node.source_file == selected_file for node in ranked_nodes):
            files.append(selected_file)
        if len(files) >= limit:
            return files

    for node in ranked_nodes[:10]:
        if node.total_score < 20:
            continue
        if node.source_file and node.source_file not in files:
            files.append(node.source_file)
        if len(files) >= limit:
            break
    return files


def generate_hot_context(ranked_nodes: list[RankedNode]) -> str:
    """Generate a Markdown hot-context note from ranked graph nodes."""
    source_files = _source_files(ranked_nodes)
    source_lines = "\n".join(f"- `{path}`" for path in source_files)
    top_suspects = _format_top_suspects(ranked_nodes)

    return f"""# Generated Hot Context

Status: generated by the Phase 6 original extension.

Links: [[index]] | [[hot]] | [[print_final_scores_global_state_bug]] | [[token_efficiency]]

## Bug Focus

{BUG_SUMMARY}

The expected modular behavior is that final-score reporting uses explicit parameters rather than hidden module state.

## Top Suspicious Graph Nodes

{top_suspects}

## Source Files To Inspect First

{source_lines}

These are intentionally limited to the two selected implementation files. Background files remain useful for context, but they are not needed for the first focused repair pass.

## Fix-Diff Integration

The Phase 4 diff confirms that the graph-selected files are also the changed files:

- `src/target_project/mathsquiz/mathsquiz_step2.py`
- `src/target_project/mathsquiz/mathsquiz_step3.py`

The boundary change is from hidden global-state reading to explicit parameter-based reporting.

## Graph Evidence

- Highest-ranked nodes combine keyword matches, graph risk labels, and proximity to selected files.
- `global_score_instead_of_param` risk nodes directly describe the official bug.
- `unused_arg:final_score` risk nodes explain why the function signature is misleading.
- Function nodes for `print_final_scores` are the primary repair targets.

## Suggested Agent Context

Use this generated note as the first active context unit, then load:

1. `reports/suspicious_nodes.md`
2. `artifacts/source_evidence/print_final_scores_source.md`
3. Only the two selected implementation files if code inspection is required

Do not load the complete `graph.json` during normal debugging unless a full audit trail is needed.

## Open Questions

- Should generated hot context replace the manual `hot.md`, or remain beside it as reproducible extension output?
- Should future ranking include runtime failure traces in addition to graph structure?
- Should the scoring weights be tuned on more than one bug path?
"""


def write_generated_hot_context(graph_path: Path, output_path: Path) -> list[RankedNode]:
    graph = load_graph(graph_path)
    ranked_nodes = rank_suspicious_nodes(graph)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(generate_hot_context(ranked_nodes), encoding="utf-8")
    return ranked_nodes


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Obsidian hot context from graph ranking.")
    parser.add_argument("--graph", default="artifacts/graphify/graph.json")
    parser.add_argument("--output", default="obsidian/hot.generated.md")
    args = parser.parse_args()

    ranked_nodes = write_generated_hot_context(Path(args.graph), Path(args.output))
    print(f"Wrote {args.output}")
    print(f"Top suspects included: {min(7, len(ranked_nodes))}")


if __name__ == "__main__":
    main()
